server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:2345/school_db?currentSchema=student_schema
  jpa:
    properties:
      hibernate:
        default_schema: student_schema
